# Generated by Django 5.2.4 on 2025-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='district',
            field=models.CharField(choices=[('Rumphi', 'Rumphi'), ('Mzuzu', 'Mzuzu'), ('Nkhata Bay', 'Nkhata Bay'), ('Mzimba', 'Mzimba'), ('Nkhotakota', 'Nkhotakota'), ('Kasungu', 'Kasungu'), ('Ntchisi', 'Ntchisi'), ('Dowa', 'Dowa'), ('Salima', 'Salima'), ('Mchinji', 'Mchinji'), ('Lilongwe', 'Lilongwe'), ('Dedza', 'Dedza'), ('Mangochi', 'Mangochi'), ('Ntcheu', 'Ntcheu'), ('Machinga', 'Machinga'), ('Balaka', 'Balaka'), ('Liwonde', 'Liwonde'), ('Zomba', 'Zomba'), ('Neno', 'Neno'), ('Mwanza', 'Mwanza'), ('Chiradzulu', 'Chiradzulu'), ('Blantyre', 'Blantyre'), ('Phalombe', 'Phalombe'), ('Mulanje', 'Mulanje'), ('Chikwawa', 'Chikwawa'), ('Thyolo', 'Thyolo'), ('Nsanje', 'Nsanje'), ('Chitipa', 'Chitipa'), ('Karonga', 'Karonga')], default='Mzuzu', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
