# Generated by Django 5.2.4 on 2025-07-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_district_name_alter_farm_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.district'),
        ),
    ]
