# Generated by Django 5.2.4 on 2025-07-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('water', 'Watering'), ('fertilize', 'Fertilizing'), ('harvest', 'Harvesting'), ('plant', 'Planting'), ('custom', 'Custom')], max_length=20)),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='farms.farm')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
