# Generated by Django 5.2.4 on 2025-07-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='is_api_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='condition',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('stormy', 'Stormy'), ('windy', 'Windy'), ('foggy', 'Foggy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
