# Generated by Django 5.2.4 on 2025-07-14 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        ('weather', '0002_weatherdata_humidity_weatherdata_is_api_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='is_api_data',
            new_name='is_forecast',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='forecast_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, default=1012.25, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='source',
            field=models.CharField(default='openweathermap', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.CharField(blank=True, default='NE', max_length=3),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='condition',
            field=models.CharField(choices=[('clear', 'Clear'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('fog', 'Fog')], default='partly_cloudy', max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rainfall',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Rainfall in mm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=24.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['farm', 'date'], name='weather_wea_farm_id_5066df_idx'),
        ),
    ]
